export type DocLink={slug:string;title:string;group:string;summary:string};
export const docs:DocLink[]=[
{slug:'introduction',title:'What is CAGE?',group:'Start',summary:'Language model, V4 philosophy and native boundaries.'},
{slug:'quick-start',title:'Quick start',group:'Start',summary:'Read a CAGE file and understand the admission pipeline.'},
{slug:'source-anatomy',title:'Source anatomy',group:'Start',summary:'Envelope, module, proof dossier, resources, functions and closure.'},
{slug:'v4-glyph-language',title:'V4 glyph language',group:'Language',summary:'Canonical Unicode, glyph identifiers and keycap numbers.'},
{slug:'types-values',title:'Types and values',group:'Language',summary:'Types, records, enums, references and explicit conversion.'},
{slug:'functions-contracts',title:'Functions and contracts',group:'Language',summary:'Effects, faults, resources and execution contracts.'},
{slug:'control-flow',title:'Control flow',group:'Language',summary:'Branches, loops, joins and invariants.'},
{slug:'constitution',title:'The Constitution',group:'Legality',summary:'Versioned laws defining legal CAGE.'},
{slug:'courts',title:'The Courts',group:'Legality',summary:'Independent legality gates.'},
{slug:'tribunal',title:'The Tribunal',group:'Legality',summary:'Final cross-law admission and execution certificates.'},
{slug:'law-concordance',title:'160-law concordance',group:'Legality',summary:'Complete legality and Tribunal concordance.'},
{slug:'fault-language',title:'Emoji fault language',group:'Faults',summary:'Machine-readable emoji-only fault packets.'},
{slug:'fault-decoders',title:'Manual fault decoders',group:'Faults',summary:'Project-authored human-readable fault mappings.'},
{slug:'fault-propagation',title:'Fault propagation and fate',group:'Faults',summary:'Recover, retry, transform, quarantine and terminate.'},
{slug:'resource-cages',title:'Resource cages',group:'Systems',summary:'Operations, time, memory, threads, handles, events and recursion.'},
{slug:'ownership',title:'Ownership and lifetimes',group:'Systems',summary:'Owned, borrowed, observed, frozen and moved states.'},
{slug:'capabilities',title:'Capabilities',group:'Systems',summary:'Explicit authority, transfers and effect conservation.'},
{slug:'concurrency',title:'Concurrency',group:'Systems',summary:'Thread ownership, race freedom and scheduling proofs.'},
{slug:'determinism',title:'Determinism and time',group:'Systems',summary:'Randomness, clocks, reproducibility and replay.'},
{slug:'state-events',title:'State and event law',group:'Applications',summary:'Transitions, event causality, focus and event budgets.'},
{slug:'ui',title:'CAGE UI',group:'Applications',summary:'Surfaces, windows, panels, labels, buttons and editors.'},
{slug:'live-runtime',title:'Live runtime authenticity',group:'Applications',summary:'Studio displays the real running CAGE scene.'},
{slug:'game-tutorial',title:'Tutorial: strict game shell',group:'Tutorials',summary:'Build the legal shell of an interactive game.'},
{slug:'ui-tutorial',title:'Tutorial: interactive UI',group:'Tutorials',summary:'Create a real scene, action and transaction.'},
{slug:'strict-headless-example',title:'Strict headless example',group:'Tutorials',summary:'Walk through the 400-plus-line admitted example.'},
{slug:'debugging',title:'Debugging CAGE',group:'Workflow',summary:'Read raw faults and repair failed Courts.'},
{slug:'native-compilation',title:'Native compilation',group:'Workflow',summary:'Frontend, verification, IR, backends and executable images.'},
{slug:'packages-passports',title:'Packages and passports',group:'Workflow',summary:'Identity, targets, closed inputs and quarantine.'},
{slug:'open-source',title:'Open-source core',group:'Reference',summary:'Published compiler, law, runtime and UI sources.'},
{slug:'glossary',title:'Glossary',group:'Reference',summary:'CAGE terminology.'}
];
export const groups=[...new Set(docs.map(d=>d.group))];
